<a href="https://colab.research.google.com/github/IamSaransh/Kaggle/blob/main/Practice/Numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy
[cs131n Numpy](https://cs231n.github.io/python-numpy-tutorial/)

**Arrays**

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [3]:
print(a.shape)

(3,)


In [4]:
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)

(2, 3)


In [5]:
all_zeros = np.zeros((2,2))
print(all_zeros)

[[0. 0.]
 [0. 0.]]


In [6]:
all_ones = np.ones((2,2))
print(all_ones)

[[1. 1.]
 [1. 1.]]


In [7]:
all_same_val = np.full((2,4),111)
print(all_same_val)

[[111 111 111 111]
 [111 111 111 111]]


In [8]:
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
random_vals = np.random.random((2,2))
print(random_vals)

[[0.13778195 0.74032765]
 [0.66736596 0.35804072]]


**Array indexing**

In [10]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
sliced_arr = arr[:2,1:3]
print(sliced_arr)


[[2 3]
 [6 7]]


In [11]:
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(arr[0, 1])   # Prints "2"
sliced_arr[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(arr[0, 1])   # Prints "77"

2
77


In [13]:


# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 2))   # Stack 4 copies of v on top of each other
print(vv)

[[1 0 1 1 0 1]
 [1 0 1 1 0 1]
 [1 0 1 1 0 1]
 [1 0 1 1 0 1]]


In [17]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = np.add(x[i,:] , v)
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
